export type { WorkSpacesWebBrowserSettings } from './workspacesweb-browsersettings'
export type { WorkSpacesWebIdentityProvider } from './workspacesweb-identityprovider'
export type { WorkSpacesWebIpAccessSettings } from './workspacesweb-ipaccesssettings'
export type { WorkSpacesWebNetworkSettings } from './workspacesweb-networksettings'
export type { WorkSpacesWebPortal } from './workspacesweb-portal'
export type { WorkSpacesWebTrustStore } from './workspacesweb-truststore'
export type { WorkSpacesWebUserAccessLoggingSettings } from './workspacesweb-useraccessloggingsettings'
export type { WorkSpacesWebUserSettings } from './workspacesweb-usersettings'
