export type { DocDBDBCluster } from './docdb-dbcluster.js'
export type { DocDBDBClusterParameterGroup } from './docdb-dbclusterparametergroup.js'
export type { DocDBDBInstance } from './docdb-dbinstance.js'
export type { DocDBDBSubnetGroup } from './docdb-dbsubnetgroup.js'
export type { DocDBEventSubscription } from './docdb-eventsubscription.js'