export type { CloudWatchAlarm } from './cloudwatch-alarm.js'
export type { CloudWatchAnomalyDetector } from './cloudwatch-anomalydetector.js'
export type { CloudWatchCompositeAlarm } from './cloudwatch-compositealarm.js'
export type { CloudWatchDashboard } from './cloudwatch-dashboard.js'
export type { CloudWatchInsightRule } from './cloudwatch-insightrule.js'
export type { CloudWatchMetricStream } from './cloudwatch-metricstream.js'