export type { AthenaCapacityReservation } from './athena-capacityreservation'
export type { AthenaDataCatalog } from './athena-datacatalog'
export type { AthenaNamedQuery } from './athena-namedquery'
export type { AthenaPreparedStatement } from './athena-preparedstatement'
export type { AthenaWorkGroup } from './athena-workgroup'
