export type { AthenaCapacityReservation } from './athena-capacityreservation.js'
export type { AthenaDataCatalog } from './athena-datacatalog.js'
export type { AthenaNamedQuery } from './athena-namedquery.js'
export type { AthenaPreparedStatement } from './athena-preparedstatement.js'
export type { AthenaWorkGroup } from './athena-workgroup.js'