export type { CloudTrailChannel } from './cloudtrail-channel.js'
export type { CloudTrailDashboard } from './cloudtrail-dashboard.js'
export type { CloudTrailEventDataStore } from './cloudtrail-eventdatastore.js'
export type { CloudTrailResourcePolicy } from './cloudtrail-resourcepolicy.js'
export type { CloudTrailTrail } from './cloudtrail-trail.js'