export type { AutoScalingAutoScalingGroup } from './autoscaling-autoscalinggroup.js'
export type { AutoScalingLaunchConfiguration } from './autoscaling-launchconfiguration.js'
export type { AutoScalingLifecycleHook } from './autoscaling-lifecyclehook.js'
export type { AutoScalingScalingPolicy } from './autoscaling-scalingpolicy.js'
export type { AutoScalingScheduledAction } from './autoscaling-scheduledaction.js'
export type { AutoScalingWarmPool } from './autoscaling-warmpool.js'