export type { Route53CidrCollection } from './route53-cidrcollection'
export type { Route53DNSSEC } from './route53-dnssec'
export type { Route53HealthCheck } from './route53-healthcheck'
export type { Route53HostedZone } from './route53-hostedzone'
export type { Route53KeySigningKey } from './route53-keysigningkey'
export type { Route53RecordSet } from './route53-recordset'
export type { Route53RecordSetGroup } from './route53-recordsetgroup'
