export type { Route53CidrCollection } from './route53-cidrcollection.js'
export type { Route53DNSSEC } from './route53-dnssec.js'
export type { Route53HealthCheck } from './route53-healthcheck.js'
export type { Route53HostedZone } from './route53-hostedzone.js'
export type { Route53KeySigningKey } from './route53-keysigningkey.js'
export type { Route53RecordSet } from './route53-recordset.js'
export type { Route53RecordSetGroup } from './route53-recordsetgroup.js'