export type { FSxDataRepositoryAssociation } from './fsx-datarepositoryassociation'
export type { FSxFileSystem } from './fsx-filesystem'
export type { FSxSnapshot } from './fsx-snapshot'
export type { FSxStorageVirtualMachine } from './fsx-storagevirtualmachine'
export type { FSxVolume } from './fsx-volume'
