export type { FSxDataRepositoryAssociation } from './fsx-datarepositoryassociation.js'
export type { FSxFileSystem } from './fsx-filesystem.js'
export type { FSxSnapshot } from './fsx-snapshot.js'
export type { FSxStorageVirtualMachine } from './fsx-storagevirtualmachine.js'
export type { FSxVolume } from './fsx-volume.js'