export type { ServiceDiscoveryHttpNamespace } from './servicediscovery-httpnamespace.js'
export type { ServiceDiscoveryInstance } from './servicediscovery-instance.js'
export type { ServiceDiscoveryPrivateDnsNamespace } from './servicediscovery-privatednsnamespace.js'
export type { ServiceDiscoveryPublicDnsNamespace } from './servicediscovery-publicdnsnamespace.js'
export type { ServiceDiscoveryService } from './servicediscovery-service.js'